### ISSUE TITLE
A non-numeric value encountered in modules/open-wp-seo-ui-settings.php on line 186

### ISSUE THREAD

**Issue by jayhybrid** [tzri/open-wordpress-seo#8]
For some reason `get_option('open_wp_seo_ping_google_time', 0)` is returning `"error"` instead of `0` and it is causing a notice for me.

**Comment by tzri** [comment]
Thanks for pointing that out. I will add this bug to the list and fix it upcoming version.

Moki-Moki

**Comment by tzri** [comment]
It's a bug.

BTW. Very nice that you are participating in the development of this project Jay!

**Comment by jayhybrid** [comment]
No problem. I would be interested if you found a fix for this, it doesn't make sense to me 🤔

**Comment by tzri** [comment]
I will take a look at it withing couple of days.
